SPANS = {
    "mission": "agent.mission",
    "context": "context.load",
    "memory": "memory.read",
    "retrieval": "retrieval.search",
    "llm": "gen_ai.chat",
    "propose": "action.propose",
    "risk": "risk.quote",
    "authorize": "policy.authorize",
    "bind": "action.bind",
    "capability": "capability.issue",
    "commit": "action.commit",
    "verify": "effect.verify",
    "replay": "replay.execute",
    "certificate": "certificate.issue",
    "suspend": "certificate.suspend",
    "rollout": "rollout.change",
    "delegate": "agent.delegate",
}

ATTRIBUTES = {
    "mission_id": "orbital.mission.id",
    "action_id": "orbital.action.id",
    "candidate_id": "orbital.candidate.id",
    "certificate_id": "orbital.certificate.id",
    "artifact_digest": "orbital.artifact.digest",
    "authority_level": "orbital.authority.level",
    "risk_class": "orbital.risk.class",
    "action_type": "orbital.action.type",
    "evidence_state": "orbital.evidence.state",
    "verdict": "orbital.certificate.verdict",
    "artifact_status": "orbital.artifact.status",
    "execution_mode": "orbital.execution.mode",
    "policy_decision": "policy.decision",
    "policy_revision": "policy.revision",
    "delegation_id": "orbital.delegation.id",
    "delegator_id": "orbital.delegation.delegator.id",
    "delegate_id": "orbital.delegation.delegate.id",
    "parent_certificate_id": "orbital.delegation.parent_certificate.id",
    "child_certificate_id": "orbital.delegation.child_certificate.id",
    "delegated_tools": "orbital.delegation.tools",
    "delegated_risk_budget": "orbital.delegation.risk_budget",
    "data_labels": "orbital.delegation.data_labels",
    "delegation_depth": "orbital.delegation.depth",
    "delegation_expiration": "orbital.delegation.expires_at",
}
