apiVersion: v1alpha1
kind: Installation
metadata:
  name: orbital
spec:
  deployment:
    flavor: compose
    mode: docker
  mcp:
    spec:
      enabled: true
      env:
        SIGNOZ_API_KEY: ${SIGNOZ_API_KEY}
